language: java
services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS hello_test;'
env: 
  - DATABASE=jdbc:mysql://localhost:3306/hello_test DB_USERNAME=travis DB_PASSWORD="" SPRING_DATASOURCE_DRIVERCLASSNAME:com.mysql.jdbc.Driver SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/hello_test SPRING_DATASOURCE_USERNAME:sa SPRING_DATASOURCE_PASSWORD:sa
